<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 18/jun/2017
 * Time: 08:20 PM
 */
?>
<div class="absolute-align">
    <div class="form-group">
        <div class="col-md-4 col-md-offset-2">
            <div class="table-responsive">
                <table class="table table-bordered" id="shots">
                    <thead>
                    <tr>
                        <th></th>
                        <th>A</th>
                        <th>B</th>
                        <th>C</th>
                        <th>D</th>
                        <th>E</th>
                        <th>F</th>
                        <th>G</th>
                        <th>H</th>
                        <th>I</th>
                        <th>J</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th>1</th>
                        <td data-id="A1"></td>
                        <td data-id="B1"></td>
                        <td data-id="C1"></td>
                        <td data-id="D1"></td>
                        <td data-id="E1"></td>
                        <td data-id="F1"></td>
                        <td data-id="G1"></td>
                        <td data-id="H1"></td>
                        <td data-id="I1"></td>
                        <td data-id="J1"></td>
                    </tr>
                    <tr>
                        <th>2</th>
                        <td data-id="A2"></td>
                        <td data-id="B2"></td>
                        <td data-id="C2"></td>
                        <td data-id="D2"></td>
                        <td data-id="E2"></td>
                        <td data-id="F2"></td>
                        <td data-id="G2"></td>
                        <td data-id="H2"></td>
                        <td data-id="I2"></td>
                        <td data-id="J2"></td>
                    </tr>
                    <tr>
                        <th>3</th>
                        <td data-id="A3"></td>
                        <td data-id="B3"></td>
                        <td data-id="C3"></td>
                        <td data-id="D3"></td>
                        <td data-id="E3"></td>
                        <td data-id="F3"></td>
                        <td data-id="G3"></td>
                        <td data-id="H3"></td>
                        <td data-id="I3"></td>
                        <td data-id="J3"></td>
                    </tr>
                    <tr>
                        <th>4</th>
                        <td data-id="A4"></td>
                        <td data-id="B4"></td>
                        <td data-id="C4"></td>
                        <td data-id="D4"></td>
                        <td data-id="E4"></td>
                        <td data-id="F4"></td>
                        <td data-id="G4"></td>
                        <td data-id="H4"></td>
                        <td data-id="I4"></td>
                        <td data-id="J4"></td>
                    </tr>
                    <tr>
                        <th>5</th>
                        <td data-id="A5"></td>
                        <td data-id="B5"></td>
                        <td data-id="C5"></td>
                        <td data-id="D5"></td>
                        <td data-id="E5"></td>
                        <td data-id="F5"></td>
                        <td data-id="G5"></td>
                        <td data-id="H5"></td>
                        <td data-id="I5"></td>
                        <td data-id="J5"></td>
                    </tr>
                    <tr>
                        <th>6</th>
                        <td data-id="A6"></td>
                        <td data-id="B6"></td>
                        <td data-id="C6"></td>
                        <td data-id="D6"></td>
                        <td data-id="E6"></td>
                        <td data-id="F6"></td>
                        <td data-id="G6"></td>
                        <td data-id="H6"></td>
                        <td data-id="I6"></td>
                        <td data-id="J6"></td>
                    </tr>
                    <tr>
                        <th>7</th>
                        <td data-id="A7"></td>
                        <td data-id="B7"></td>
                        <td data-id="C7"></td>
                        <td data-id="D7"></td>
                        <td data-id="E7"></td>
                        <td data-id="F7"></td>
                        <td data-id="G7"></td>
                        <td data-id="H7"></td>
                        <td data-id="I7"></td>
                        <td data-id="J7"></td>
                    </tr>
                    <tr>
                        <th>8</th>
                        <td data-id="A8"></td>
                        <td data-id="B8"></td>
                        <td data-id="C8"></td>
                        <td data-id="D8"></td>
                        <td data-id="E8"></td>
                        <td data-id="F8"></td>
                        <td data-id="G8"></td>
                        <td data-id="H8"></td>
                        <td data-id="I8"></td>
                        <td data-id="J8"></td>
                    </tr>
                    <tr>
                        <th>9</th>
                        <td data-id="A9"></td>
                        <td data-id="B9"></td>
                        <td data-id="C9"></td>
                        <td data-id="D9"></td>
                        <td data-id="E9"></td>
                        <td data-id="F9"></td>
                        <td data-id="G9"></td>
                        <td data-id="H9"></td>
                        <td data-id="I9"></td>
                        <td data-id="J9"></td>
                    </tr>
                    <tr>
                        <th>10</th>
                        <td data-id="A10"></td>
                        <td data-id="B10"></td>
                        <td data-id="C10"></td>
                        <td data-id="D10"></td>
                        <td data-id="E10"></td>
                        <td data-id="F10"></td>
                        <td data-id="G10"></td>
                        <td data-id="H10"></td>
                        <td data-id="I10"></td>
                        <td data-id="J10"></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4">
            <div class="table-responsive">
                <table class="table table-bordered" id="ships">
                    <thead>
                    <tr>
                        <th></th>
                        <th>A</th>
                        <th>B</th>
                        <th>C</th>
                        <th>D</th>
                        <th>E</th>
                        <th>F</th>
                        <th>G</th>
                        <th>H</th>
                        <th>I</th>
                        <th>J</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <th>1</th>
                        <td data-id="A1"></td>
                        <td data-id="B1"></td>
                        <td data-id="C1"></td>
                        <td data-id="D1"></td>
                        <td data-id="E1"></td>
                        <td data-id="F1"></td>
                        <td data-id="G1"></td>
                        <td data-id="H1"></td>
                        <td data-id="I1"></td>
                        <td data-id="J1"></td>
                    </tr>
                    <tr>
                        <th>2</th>
                        <td data-id="A2"></td>
                        <td data-id="B2"></td>
                        <td data-id="C2"></td>
                        <td data-id="D2"></td>
                        <td data-id="E2"></td>
                        <td data-id="F2"></td>
                        <td data-id="G2"></td>
                        <td data-id="H2"></td>
                        <td data-id="I2"></td>
                        <td data-id="J2"></td>
                    </tr>
                    <tr>
                        <th>3</th>
                        <td data-id="A3"></td>
                        <td data-id="B3"></td>
                        <td data-id="C3"></td>
                        <td data-id="D3"></td>
                        <td data-id="E3"></td>
                        <td data-id="F3"></td>
                        <td data-id="G3"></td>
                        <td data-id="H3"></td>
                        <td data-id="I3"></td>
                        <td data-id="J3"></td>
                    </tr>
                    <tr>
                        <th>4</th>
                        <td data-id="A4"></td>
                        <td data-id="B4"></td>
                        <td data-id="C4"></td>
                        <td data-id="D4"></td>
                        <td data-id="E4"></td>
                        <td data-id="F4"></td>
                        <td data-id="G4"></td>
                        <td data-id="H4"></td>
                        <td data-id="I4"></td>
                        <td data-id="J4"></td>
                    </tr>
                    <tr>
                        <th>5</th>
                        <td data-id="A5"></td>
                        <td data-id="B5"></td>
                        <td data-id="C5"></td>
                        <td data-id="D5"></td>
                        <td data-id="E5"></td>
                        <td data-id="F5"></td>
                        <td data-id="G5"></td>
                        <td data-id="H5"></td>
                        <td data-id="I5"></td>
                        <td data-id="J5"></td>
                    </tr>
                    <tr>
                        <th>6</th>
                        <td data-id="A6"></td>
                        <td data-id="B6"></td>
                        <td data-id="C6"></td>
                        <td data-id="D6"></td>
                        <td data-id="E6"></td>
                        <td data-id="F6"></td>
                        <td data-id="G6"></td>
                        <td data-id="H6"></td>
                        <td data-id="I6"></td>
                        <td data-id="J6"></td>
                    </tr>
                    <tr>
                        <th>7</th>
                        <td data-id="A7"></td>
                        <td data-id="B7"></td>
                        <td data-id="C7"></td>
                        <td data-id="D7"></td>
                        <td data-id="E7"></td>
                        <td data-id="F7"></td>
                        <td data-id="G7"></td>
                        <td data-id="H7"></td>
                        <td data-id="I7"></td>
                        <td data-id="J7"></td>
                    </tr>
                    <tr>
                        <th>8</th>
                        <td data-id="A8"></td>
                        <td data-id="B8"></td>
                        <td data-id="C8"></td>
                        <td data-id="D8"></td>
                        <td data-id="E8"></td>
                        <td data-id="F8"></td>
                        <td data-id="G8"></td>
                        <td data-id="H8"></td>
                        <td data-id="I8"></td>
                        <td data-id="J8"></td>
                    </tr>
                    <tr>
                        <th>9</th>
                        <td data-id="A9"></td>
                        <td data-id="B9"></td>
                        <td data-id="C9"></td>
                        <td data-id="D9"></td>
                        <td data-id="E9"></td>
                        <td data-id="F9"></td>
                        <td data-id="G9"></td>
                        <td data-id="H9"></td>
                        <td data-id="I9"></td>
                        <td data-id="J9"></td>
                    </tr>
                    <tr>
                        <th>10</th>
                        <td data-id="A10"></td>
                        <td data-id="B10"></td>
                        <td data-id="C10"></td>
                        <td data-id="D10"></td>
                        <td data-id="E10"></td>
                        <td data-id="F10"></td>
                        <td data-id="G10"></td>
                        <td data-id="H10"></td>
                        <td data-id="I10"></td>
                        <td data-id="J10"></td>
                    </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
