<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 07/jun/2017
 * Time: 11:39 AM
 */
/** @var controller\Login $controller */
?>
<div class="absolute-align">
    <div class="form-group">
        <div class="col-md-4 col-md-offset-4">
            <input class="form-control" placeholder="User">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-4 col-md-offset-4">
            <input class="form-control" placeholder="Password">
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-4 col-md-offset-4">
            <a class="btn btn-primary col-md-12">Log In</a>
        </div>
    </div>
</div>
