<?php
/**
 * Created by PhpStorm.
 * User: Cachu
 * Date: 18/jun/2017
 * Time: 09:05 PM
 */
/** @var string $body */
/** @var string $view */
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Battleship</title>
    <link rel="stylesheet" href="resources/plugins/bootstrap-3.3.7/css/bootstrap.css">
    <link rel="stylesheet" href="resources/css/template.css">
    <link rel="stylesheet" href="resources/css/<?= $view ?>.css">
</head>
<body>
<div class="container">
    <form id="frmSistema" class="form-horizontal">
        <?= $body ?>
    </form>
</div>
<script src="resources/plugins/jquery/jquery-3.2.1.js"></script>
<script src="resources/plugins/bootstrap-3.3.7/js/bootstrap.js"></script>
</body>
</html>